### PR TITLE
Field mappings + Alert Details Widget

### PR DESCRIPTION
**Pull request by antazoey**
* Adds new fields
* Makes some logic more functional (but nothing changed there).

Big note on this -- some of the default mapping required to get this to work are not included.... in server 6.0.0, they are, but it seems like it's pretty common for analysts to come in and mess all that up anyway, if that makes sense.

I can explain how to get the mappings to work in the Confluence page.

### CODE REVIEW

**Comment by antazoey** [comment]
This one might require  a demo - @kiran-chaudhary  saw it a little bit in that last demo I did.. I will attach a photo

**Comment by antazoey** [comment]
[
Screen Shot 2020-06-26 at 16 24 26
](url)

**Comment by antazoey** [comment]
In the pic above, you will see the "Code42 Alert Details" section - that is really all that changed, besides something to make the File Events table work.

**Review by alanag13 — APPROVED** [review]
Even though I don't have much context here I'm willing to approve this since it seems to be basically just configuration and i figure PAN will tell you if something is wrong here once we go to merge with them.

**Pull request merged**
